services:
  sm-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.sm
    restart: unless-stopped
    depends_on:
      db-sm:
        condition: service_healthy
    volumes:
      - ./log/soccer-manager.log:/log/logs.log
  db-sm:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - db-sm:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=sm
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d sm'"]
      interval: 3s
      timeout: 3s
      retries: 60
  swagger-ui:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.swagger
    restart: unless-stopped
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - sm-service
    volumes:
      - ./log/access.log:/var/log/nginx/access.log

volumes:
  db-sm:
    driver: local
