server:
  instance_id: 1
  shutdown_timeout: 10s
  max_file_size: 10

http:
  port: 80
  cors_origins: "*"
  idle_timeout: 60s
  read_timeout: 10s
  write_timeout: 30s

metrics:
  port: 8081

logging:
  dev_level: debug
  prod_level: info
  caller_enabled: true

jwt:
  access:
    ttl: 2h
  refresh:
    ttl: 168h

pagination:
  s: 10
  m: 25
  l: 50
  xl: 100
  2xl: 150
